"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { ClipboardCheck, Landmark, MessageCircle, Send, Truck } from "lucide-react";
import { submitSupplierDeliveryNoticeAction, submitSupplierPurchaseOrderResponseAction } from "@/app/portal-actions";
import { PartnerConversation } from "@/components/partner-conversation";
import { PushNotificationControl } from "@/components/push-notification-control";
import type { SupplierPortalReadModel } from "@/server/erp-v2/partner-portal-read-model";

export function SupplierPortalWorkspace({ model, activePath = "/nha-cung-cap" }: { model: SupplierPortalReadModel; activePath?: string }) {
  const [message, setMessage] = useState<string>();
  const [pending, startTransition] = useTransition();
  const outstanding = Math.max(0, model.payable - model.overpayment);
  return <>
    <section className="customer-hero" aria-labelledby="supplier-portal-title"><div><p className="customer-eyebrow">Thông tin dành cho nhà cung cấp</p><h1 id="supplier-portal-title">Chào {model.supplier.displayName}</h1><p>Xem đơn mua của cửa hàng, trả lời khả năng cung cấp và báo hàng đã giao để cửa hàng kiểm tra.</p></div><Truck aria-hidden="true" /></section>
    <section className="supplier-summary-grid" aria-label="Tóm tắt nhà cung cấp"><article><ClipboardCheck aria-hidden="true" /><span>Đơn mua cần trả lời</span><strong>{model.orders.filter((order) => order.status !== "fully_received").length}</strong></article><article><Landmark aria-hidden="true" /><span>Cửa hàng cần thanh toán</span><strong>{formatCurrency(outstanding)}</strong><span>Cửa hàng sẽ thông báo hạn thanh toán.</span></article></section>
    <div className="supplier-portal-workspace"><div className="supplier-portal-primary">
      <section className="supplier-orders-panel" aria-labelledby="supplier-orders-title"><div className="customer-panel-heading"><div><p className="customer-eyebrow">Đơn mua của cửa hàng</p><h2 id="supplier-orders-title">Trả lời và báo giao hàng</h2></div><ClipboardCheck aria-hidden="true" /></div>
        {model.orders.length ? <div className="supplier-order-list">{model.orders.map((order) => <article className="supplier-order" key={order.id}>
          <div className="supplier-order-heading"><div><strong><Link href={`/nha-cung-cap/don-mua/${order.id}`}>{order.documentNo}</Link></strong><span>{formatDate(order.orderDate)} · {statusLabel(order.status)}</span></div><b>{order.responseCount} lần trả lời · {order.noticeCount} lần báo giao</b></div>
          {order.latestResponse ? <p className="supplier-response-summary"><strong>Phản hồi gần nhất:</strong> {order.latestResponse.status === "available" ? "Có thể cung cấp" : "Chưa thể cung cấp"}{order.expectedDeliveryDate ? ` · dự kiến ${formatDate(order.expectedDeliveryDate)}` : ""}{order.latestResponse.note ? ` · ${order.latestResponse.note}` : ""}</p> : <p className="supplier-response-summary">Chưa gửi phản hồi khả năng cung cấp.</p>}
          <div className="supplier-order-lines">{order.lines.map((line) => <div key={line.id}><span><strong>{line.productName}</strong><small>{line.destination}</small></span><span>{formatQuantity(line.orderedQuantity)} {line.unitName}</span><span>Đã nhận: {formatQuantity(line.receivedQuantity)}</span><b>{formatCurrency(line.unitCost * line.orderedQuantity * (1 + line.taxRate))}</b></div>)}</div>
          {order.deliveryNotices.length ? <details className="supplier-notice-history"><summary>Lịch sử báo giao ({order.deliveryNotices.length})</summary><ul>{order.deliveryNotices.map((notice) => <li key={notice.id}><strong>{formatDate(notice.submittedAt)}</strong><span>{Object.entries(notice.lineQuantities).map(([lineId, quantity]) => `${order.lines.find((line) => line.id === lineId)?.productName ?? lineId}: ${formatQuantity(quantity)}`).join(" · ")}</span>{notice.note ? <small>{notice.note}</small> : null}<small>{notice.attachmentCount ? `${notice.attachmentCount} tệp riêng tư` : "Không có tệp đính kèm"}</small></li>)}</ul></details> : null}
          <div className="supplier-order-actions">
            <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await submitSupplierPurchaseOrderResponseAction({ idempotencyKey: createPortalKey("supplier-response"), purchaseOrderId: order.id, status: form.get("status"), proposedDeliveryDate: form.get("proposedDeliveryDate") || undefined, note: form.get("note") || undefined }); setMessage(result.message); }); }}><label>Khả năng cung cấp<select name="status" defaultValue="available"><option value="available">Có thể cung cấp</option><option value="unavailable">Chưa thể cung cấp</option></select></label><label>Ngày giao dự kiến<input name="proposedDeliveryDate" type="date" /></label><label>Ghi chú<textarea name="note" rows={2} maxLength={1000} placeholder="Ví dụ: giao thành hai đợt" /></label><button className="button button-secondary" type="submit" disabled={pending}><MessageCircle aria-hidden="true" />{pending ? "Đang gửi..." : "Gửi trả lời"}</button></form>
            <form encType="multipart/form-data" onSubmit={(event) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); form.set("purchaseOrderId", order.id); form.set("idempotencyKey", createPortalKey("supplier-delivery")); startTransition(async () => { const result = await submitSupplierDeliveryNoticeAction(form); setMessage(result.message); if (result.ok) formElement.reset(); }); }}><p className="supplier-action-title">Báo hàng đã giao</p>{order.lines.filter((line) => line.remainingQuantity > 0).map((line) => <label key={line.id}>Số lượng {line.productName}<input name={`line:${line.id}`} type="number" min="0" max={line.remainingQuantity} step="any" placeholder="0" /></label>)}<label>Ghi chú giao hàng<textarea name="note" rows={2} maxLength={1000} placeholder="Thông tin xe, người giao hoặc ghi chú" /></label><label>Ảnh hoặc chứng từ giao hàng<input name="attachment" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" /></label><button className="button button-primary" type="submit" disabled={pending}><Send aria-hidden="true" />{pending ? "Đang gửi..." : "Gửi báo giao để cửa hàng duyệt"}</button></form>
          </div>
        </article>)}</div> : <p className="customer-empty">Chưa có đơn mua nào cần xử lý.</p>}
        {message ? <p className="supplier-portal-message" role="status" aria-live="polite">{message}</p> : null}
      </section>
      <section className="customer-portal-grid"><article className="customer-panel"><div className="customer-panel-heading"><div><p className="customer-eyebrow">Thanh toán</p><h2>Các lần cửa hàng đã thanh toán</h2></div><Landmark aria-hidden="true" /></div>{model.payments.length ? <ul className="customer-entry-list">{model.payments.map((entry) => <li key={entry.id}><div><strong>{entry.documentNo}</strong><span>Đã thanh toán ngày {formatDate(entry.date)}</span></div><b className="customer-entry-credit">{formatCurrency(entry.amount)}</b></li>)}</ul> : <p className="customer-empty">Chưa có lần thanh toán nào.</p>}</article><article className="customer-panel"><div className="customer-panel-heading"><div><p className="customer-eyebrow">Cửa hàng sẽ kiểm tra</p><h2>Trả lời và báo giao</h2></div><ClipboardCheck aria-hidden="true" /></div><p className="customer-empty">Sau khi bạn gửi, cửa hàng sẽ kiểm tra rồi thông báo lại. Số tiền chưa thay đổi ngay.</p></article></section>
    </div><aside className="supplier-portal-sidebar" aria-label="Trao đổi với cửa hàng" id="tin-nhan"><PartnerConversation partyType="supplier" partyId={model.supplier.id} partyLabel="Cửa hàng VLXD Hiền Xa" title="Nhắn tin với cửa hàng" compact /></aside></div>
    <PushNotificationControl />
  </>;
}

function createPortalKey(prefix: string) { return `${prefix}-${Date.now()}-${window.crypto.randomUUID()}`; }
function formatCurrency(value: number) { return new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(value); }
function formatQuantity(value: number) { return new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 3 }).format(value); }
function formatDate(value: string) { return new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeZone: "Asia/Ho_Chi_Minh" }).format(new Date(value)); }
function statusLabel(status: SupplierPortalReadModel["orders"][number]["status"]) { return ({ ordered: "Đã xác nhận", partially_received: "Đang nhận hàng", fully_received: "Đã nhận đủ", draft: "Đang soạn" })[status]; }
